version: '3.2'

services:
  sbtc:
    image: sbtc:latest
    container_name: sbtc
    build:
      context: ./docker
      args:
        SBTC_VERSION: 'Alpha Romeo'
        GIT_URI: 'https://github.com/Trust-Machines/stacks-sbtc.git'
        GIT_BRANCH: 'master'
    command: /bin/sh
