version: '3.2'

services:
  bitcoin:
    image: bitcoin:latest
    container_name: bitcoin
    build:
      context: ./bitcoin/docker
    command: bash -c "/srv/explorer/run.sh bitcoin-regtest explorer"
    ports:
      - 50001:50001
      - 18444:18444
      - 18443:18443
      - 8094:80
    environment:
      - NO_REGTEST_MINING=1
      - DEBUG=verbose
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  stacks:
    image: stacks:latest
    container_name: stacks
    build:
      context: ./stacks/docker
      args:
        STACKS_NODE_VERSION: '2.4.0.0.0'
        GIT_URI: https://github.com/stacks-network/stacks-blockchain.git
        GIT_BRANCH: 2.4.0.0.0
    ports:
      - 20444:20444
      - 20443:20443
    depends_on:
      - bitcoin
    environment:
      - STACKS_LOG_DEBUG=0
      - STACKS_LOG_JSON=0
      - STACKS_NETWORK=mocknet
  stacks-api:
    image: stacks-api:latest
    container_name: stacks-api
    build:
      context: ./stacks-api/docker
      args:
       GIT_URI: 'https://github.com/hirosystems/stacks-blockchain-api.git'
       GIT_BRANCH: 'v7.3.0'
    ports:
      - 3999:3999
      - 3700:3700 
    depends_on:
      - postgres
      - stacks
      - bitcoin
    environment:
      - NODE_ENV=production
      - GIT_TAG=master
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=postgres
      - STACKS_CHAIN_ID=0x80000000
      - V2_POX_MIN_AMOUNT_USTX=90000000260
      - STACKS_CORE_EVENT_PORT=3700
      - STACKS_CORE_EVENT_HOST=0.0.0.0
      - STACKS_BLOCKCHAIN_API_PORT=3999
      - STACKS_BLOCKCHAIN_API_HOST=0.0.0.0
      - STACKS_CORE_RPC_HOST=stacks
      - STACKS_CORE_RPC_PORT=20443
      - API_DOCS_URL=http://localhost:3999/doc
  stacks-explorer:
    image: stacks-explorer
    container_name: stacks-explorer
    build:
      context: ./stacks-explorer/docker
      args:
        STACKS_EXPLORER_VERSION: 'v1.119.0'
        GIT_URI: https://github.com/hirosystems/explorer.git
        GIT_BRANCH: v1.119.0
    ports:
      - 3000:3000
    depends_on:
      - bitcoin
      - stacks
      - stacks-api
      - postgres
    environment:
      - NEXT_PUBLIC_MAINNET_API_SERVER=http://127.0.0.1:3999
